apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloudstorex

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - serviceaccount.yaml
  - deployment-backend.yaml
  - deployment-frontend.yaml
  - statefulset-postgres.yaml
  - statefulset-redis.yaml
  - statefulset-minio.yaml
  - service-backend.yaml
  - service-frontend.yaml
  - service-postgres.yaml
  - service-redis.yaml
  - service-minio.yaml
  - ingress.yaml
  - hpa-backend.yaml
  - pdb-backend.yaml
  - networkpolicy.yaml
