apiVersion: v1
kind: Namespace
metadata:
  name: cloudstorex
  labels:
    app.kubernetes.io/name: cloudstorex
    app.kubernetes.io/part-of: cloudstorex-control-plane
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
