apiVersion: v1
kind: Secret
metadata:
  name: cloudstorex-secret
  labels:
    app.kubernetes.io/name: cloudstorex
    app.kubernetes.io/component: secret
type: Opaque
stringData:
  DB_PASSWORD: "supersecretpgpassword"
  JWT_SECRET: "supersecretjwtkey12345678901234567890"
  MINIO_ACCESS_KEY: "cloudstorexadmin"
  MINIO_SECRET_KEY: "cloudstorexsecretpassword"
