apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudstorex-sa
  labels:
    app.kubernetes.io/name: cloudstorex
    app.kubernetes.io/component: security
  annotations:
    # Optional annotation for AWS IAM Roles for Service Accounts (IRSA)
    eks.amazonaws.com/role-arn: ""
automountServiceAccountToken: true
