apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cloudstorex.fullname" . }}-config
  labels:
    {{- include "cloudstorex.labels" . | nindent 4 }}
data:
  APP_ENV: {{ .Values.global.environment | quote }}
  PORT: {{ .Values.backend.service.port | quote }}
  DB_HOST: {{ include "cloudstorex.dbHost" . | quote }}
  DB_PORT: "5432"
  DB_NAME: {{ include "cloudstorex.dbName" . | quote }}
  DB_USER: {{ include "cloudstorex.dbUser" . | quote }}
  REDIS_HOST: {{ include "cloudstorex.redisHost" . | quote }}
  REDIS_PORT: "6379"
  MINIO_ENDPOINT: {{ include "cloudstorex.storageEndpoint" . | quote }}
  MINIO_BUCKET: {{ include "cloudstorex.storageBucket" . | quote }}
  MINIO_USE_SSL: "false"
  CORS_ALLOWED_ORIGINS: {{ .Values.backend.env.CORS_ALLOWED_ORIGINS | quote }}
  MAX_UPLOAD_SIZE_MB: {{ .Values.backend.env.MAX_UPLOAD_SIZE_MB | quote }}
