apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloudstorex.fullname" . }}-secret
  labels:
    {{- include "cloudstorex.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_PASSWORD: {{ include "cloudstorex.dbPassword" . | quote }}
  JWT_SECRET: {{ .Values.backend.env.JWT_SECRET | quote }}
  MINIO_ACCESS_KEY: {{ include "cloudstorex.storageAccessKey" . | quote }}
  MINIO_SECRET_KEY: {{ include "cloudstorex.storageSecretKey" . | quote }}
