{{- if .Values.minio.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloudstorex.fullname" . }}-minio
  labels:
    {{- include "cloudstorex.labels" . | nindent 4 }}
    app.kubernetes.io/component: minio
spec:
  type: ClusterIP
  selector:
    {{- include "cloudstorex.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: minio
  ports:
    - name: api
      port: {{ .Values.minio.service.apiPort }}
      targetPort: 9000
    - name: console
      port: {{ .Values.minio.service.consolePort }}
      targetPort: 9001
{{- end }}
