apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloudstorex.fullname" . }}-backend
  labels:
    {{- include "cloudstorex.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    {{- include "cloudstorex.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: 8080
      protocol: TCP
