apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloudstorex.fullname" . }}-frontend
  labels:
    {{- include "cloudstorex.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    {{- include "cloudstorex.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: 3000
      protocol: TCP
