DB_HOST: "127.0.0.1"
DB_PORT: "5432"
DB_USER: "cloudstorex"
DB_PASSWORD: "password"
DB_NAME: "cloudstorex"
REDIS_HOST: "127.0.0.1"
REDIS_PORT: "6379"
MINIO_ENDPOINT: "127.0.0.1:9000"
MINIO_ACCESS_KEY: "minioadmin"
MINIO_SECRET_KEY: "minioadmin"
