apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloudstorex

resources:
  - ../../base

patches:
  - path: configmap-patch.yaml
  - path: replica-patch-backend.yaml
  - path: replica-patch-frontend.yaml
  - path: resource-patch.yaml
